# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongo'
gem 'bson_ext'
# gem "rails"
gem 'activesupport'
gem 'rake'
gem 'nokogiri'
gem 'sidekiq'
gem 'octokit'
gem 'pry'
gem 'puma'
